global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: healthbook-api
    metrics_path: /metrics
    static_configs:
      - targets: ["healthbook-api:3000"]

  - job_name: tracking-api
    metrics_path: /metrics
    static_configs:
      - targets: ["tracking-api:3000"]

  - job_name: data-recommendation-api
    metrics_path: /metrics
    static_configs:
      - targets: ["data-recommendation-api:3000"]
